mhwc-cbor = bytes .cbor measured-hw-component
mhhwc-json = text .json measured-hw-component

; EAT CBOR (`.feature "cbor"`)
$measurements-body-cbor /= mhwc-cbor

; EAT JSON (`.feature "json"`)
$measurements-body-json /= mhwc-json

measured-hw-component = {
      component-id-label => component-id
      measurement-list-label => [ + hw-measurement ]
   }

hw-measurement = {
      measurement-unit-id => tstr
      measurement-type        ;a choice
      measurement-value-label ; depends of type
   }

measurement-value-label = {
   ; structure that depends of type
}

