
mhwc-cbor = bytes .cbor measured-hw-component
mhhwc-json = text .json measured-hw-component

; EAT CBOR (`.feature "cbor"`)
$measurements-body-cbor /= mhwc-cbor

; EAT JSON (`.feature "json"`)
$measurements-body-json /= mhwc-json

measured-hw-component = {
      component-id-label => component-id
      ? operational-ctx-label => operational-ctx
      measurement-list-label => [ + hw-measurement ]
   }

operational-ctx = {
   ; structure for operational context
}

hw-measurement = {
      measurement-unit-id => tstr
      measurement-type-label => measurement-type   ; a choice
      measurement-value-label => measurement-value ; depends of type
   }

measurement-type =
   mt-self-test /
   mt-phys-prop /
   mt-event /
   mt-trace /
   mt-other ; profile

measurement-value = ; structure that depends of type
   mv-self-test /
   mv-phys-prop /
   mv-event /
   mv-trace /
   mv-other ; profile

mv-phys-prop = {
   physical-property-id => tstr,
   value => number / bstr / tstr,
   ; unit, precision, scale, uncertainty,
   ; are already specified in Endrorsements
}

mv-self-test = {
   test-id => tstr,
   test-result-label => self-test-result,
}

self-test-result =
    st-pass /
    st-fail /
    st-degraded /
    st-not-run /
    st-unknown

mv-event = {
  event-id => tstr,
  event-status-label => event-status,
  ? event-count => uint,
  ? event-time => int / uint
}

event-status =
    e-detected /
    e-not-detected /
    e-active /
    e-inactive /
    e-unknown

mv-trace = {
  trace-type-label => trace-type,
  trace-data => bstr / tstr
}

trace-type =
    digest /
    summary /
    counter

