 measured-hw-component = {
      ; TODO
      ; - identify the component
      ; - type of measurement (BIST, KAT, physical property)
      ; - measurement value (need to be able to hold
      ; many types of measurements)
      ; could also be a digest option for optimization
   }

 measured-hw-component = {
      component-id-label => component-id
      measurement-list-label => [ + hw-measurement ]
   }

hw-measurement = {
      measurement-type
      measurement-value
   }

