
measured-hw-component = {
      component-id-label => component-id
      ? operational-ctx-label => operational-ctx
      measurement-list-label => [ + hw-measurement ]
   }

operational-ctx = {
   ; structure for operational context
}

hw-measurement = {
      measurement-unit-id => tstr
      measurement-type-label => measurement-type         ; a choice
      measurement-value-label => measurement-value ; depends of type
   }

measurement-type =
   mt-self-test /
   mt-phys-prop /
   mt-event /
   mt-trace /
   mt-other ; profile

measurement-value = ; structure that depends of type
   mv-self-test /
   mv-phys-prop /
   mv-event /
   mv-trace /
   mv-other ; profile

