   mhwc-cbor = bytes .cbor measured-hw-component
   mhhwc-json = text .json measured-hw-component

   ; EAT CBOR (`.feature "cbor"`)
   $measurements-body-cbor /= mhwc-cbor

   ; EAT JSON (`.feature "json"`)
   $measurements-body-json /= mhwc-json

   measured-component = {
      ; TODO
      ; - need to identify the component
      ; - put a type of measurement (BIST, KAT, physical prop monitor)
      ; - measurement value (need to be able to hold
      ; many types of measurements)
   }
